DBusService: Call list() on classes for QueryAvailablePlugins
In python3 dict.keys() does not return a list and Gio is much more strict
which caused an exception.

GLib.Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.IOError: Method org.blueman.Applet.QueryAvailablePlugins failed with: 'dict_keys' object is not subscriptable (5)