Handle missing __author__ or __description__ in plugins
It could be done with hasattr() but this would be ugly so instead have
a default on the BasePlugin class

Traceback (most recent call last):
  File "/home/sander/repos/blueman/blueman/gui/applet/PluginDialog.py", line 192, in on_selection_changed
    self.author_txt.props.label = cls.__author__ or _("Unspecified")
AttributeError: type object 'AutoConnect' has no attribute '__author__'